# fly.toml app configuration file generated for entidades-mexicanos on 2024-12-31T12:07:36-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'entidades-mexicanos'
primary_region = 'qro'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[[mounts]]
  source="mexico_data"
  destination="/data"
  initial_size="1GB"

[env]
  # Replace this URL with your Dropbox link
  INEGI_DATA_URL="https://www.dropbox.com/scl/fi/d2l99xo7z9h9ugesa81rt/municipios_mexicanos_utf_8.csv?rlkey=6tlcr237ol33fx9tlzb17aajw&dl=0"
